---
- name: Create Data Directory - ChromaDB
  ansible.builtin.file:
    path: "{{ chromadb_data_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Pull the Docker Image - ChromaDB
  community.docker.docker_image:
    name: "{{ chromadb_image }}:{{ chromadb_version }}"
    source: pull

- name: Run the Docker Container - ChromaDB
  community.docker.docker_container:
    name: "{{ chromadb_container_name }}"
    image: "{{ chromadb_image }}:{{ chromadb_version }}"
    state: started
    restart_policy: "{{ chromadb_restart_policy }}"
    published_ports:
      - "{{ chromadb_port }}:8000"
    volumes:
      - "{{ chromadb_data_dir }}:/chroma/chroma"
    env:
      IS_PERSISTENT: "TRUE"

- name: Verify the container is running - ChromaDB
  community.docker.docker_container_info:
    name: "{{ chromadb_container_name }}"
  register: chroma_info

- name: Show Container Status - ChromaDB
  ansible.builtin.debug:
    msg: "ChromaDB is running : {{ chroma_info.container.State.Running }}"
