---
# file: clickhouse/tasks/installation.yml

- name: Make sure the CA certificates are available
  ansible.builtin.apt:
    pkg: ca-certificates

- name: Add ClickHouse repository
  ansible.builtin.deb822_repository:
    name: clickhouse
    types: deb
    uris: http://repo.yandex.ru/clickhouse/deb/stable
    suites: main
    signed_by: "{{ clickhouse_apt_key_url }}"
    state: present

- name: Install ClickHouse packages
  ansible.builtin.apt:
    name: "{{ item.pkg }}"
    state: "{{ item.state }}"
    update_cache: true
    cache_valid_time: 600
  with_items:
    - "{{ clickhouse_apt_packages }}"
