# geerlingguy.ntp overrides for Ubuntu 24.04
ntp_enabled: true
ntp_package: chrony
ntp_daemon: chronyd
ntp_config_file: /etc/chrony/chrony.conf
ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"
