# code: language=ansible
# vim: set filetype=yaml.ansible :
---
- name: "vw : docker compose up"
  community.docker.docker_compose_v2:
    state: present
    project_src: "{{ vaultwarden_docker_root_folder }}"

- name: "vw : docker compose restart"
  community.docker.docker_compose_v2:
    project_src: "{{ vaultwarden_docker_root_folder }}"
    state: restarted
    services:
      - "{{ vaultwarden_docker_container_name }}"
