---
roles:
  # ---------------------------#
  #       Networking          #
  # ---------------------------#

  # Networking / VPN - Tailscale
  - name: tailscale
    src: artis3n.tailscale
    version: "v5.0.1"

  # DNS / AdBlocking - Adguard
  - name: adguardhome
    src: bcook254.adguardhome
    version: "107.77.0"

  # Reverse Proxy - Traefik
  - name: traefik
    src: arillso.traefik
    version: "1.0.2"

  # --------------------------- #
  #        Infrastructure       #
  # --------------------------- #

  # Identity - Authentik
  - name: authentik
    src: ax-bzh.authentik
    version: "1.0.0"

  # Password Vault - Vaultwarden
  - name: vaultwarden
    src: foi.vaultwarden_docker
    version: "1.0.7"

  # NTP - Time Sync
  - name: ntp
    src: geerlingguy.ntp
    version: "2.5.0"

  # --------------------------- #
  #            Data             #
  # --------------------------- #

  # Database - Postgres SQL - Extend role into Pg Vector
  - name: postgresql
    src: geerlingguy.postgresql
    version: "4.1.0"

  # Database - MongoDB NOSQL
  - name: mongodb
    src: trfore.mongodb_install
    version: "v3.0.4"

  # Caching - Redis
  - name: redis
    src: geerlingguy.redis
    version: "1.9.1"

  # Monitoring - Clickhouse
  - name: clickhouse
    src: kostiantyn-nemchenko.clickhouse
  # Tracks main for version

  # Qdrant — no Galaxy role exists, built in custom data_tier role
  # ChromaDB — no Galaxy role exists, built in custom data_tier role
  # MinIO — no strong Galaxy role, built in custom data_tier role
  # Uptime Kuma Watch Dog - no strong Galaxy role, built in custom data_tier
  # Backup Cron - Write Custom Role

  # --------------------------- #
  #            Platform         #
  # --------------------------- #

  # Compute - Kubernetes (k3's + Docker)
  - name: docker
    src: geerlingguy.docker
    version: "3.0.0"

  - name: k3s
    src: xanmanning.k3s
    version: "v3.4.0"

collections:
  - name: community.docker
    version: ">=3.8.0"

  - name: community.general
    version: ">=8.0.0"
