---
common_timezone: America/Phoenix
common_dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  - 192.168.0.110

common_dns_search:
  - platform.local
  - homelab

common_packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - python3
  - python3-pip
  - qemu-guest-agent
  - unzip
  - ca-certificates
