---
# file: clickhouse/handlers/main.yml

- name: Start ClickHouse
  ansible.builtin.service:
    name: clickhouse-server
    state: running
    enabled: true
    pattern: /usr/bin/clickhouse-server

- name: Restart ClickHouse
  ansible.builtin.service:
    name: clickhouse-server
    state: restarted
