---
mongodb_version: "8.0.9"
mongodb_version_maj: '{{ mongodb_version | regex_search("^\d") }}'
mongodb_version_maj_minor: '{{ mongodb_version | regex_search("^\d.\d") }}'
mongodb_path_exec: /usr/bin

# package install variables
# yamllint disable-line rule:line-length
mongodb_gpg_key: "https://pgp.mongodb.com/server-{{ mongodb_version_maj_minor }}.asc"
mongodb_pkg_hold: true

# systemd unit limit variables
mongodb_systemd_unit_limit_nofile: 64000
mongodb_systemd_unit_limit_nproc: 64000

# network variables
# Comma separated list of ip addresses to listen on
mongodb_net_bindip: 127.0.0.1
# Port to listen on
mongodb_net_port: 27017
# Enable or disable ssl connections
mongodb_net_ssl: disabled
# Set the ssl mode (RequireSSL / preferSSL / AllowSSL / disabled)
mongodb_net_ssl_mode: ""
# Location of the pemfile to use for ssl
mongodb_net_ssl_pemfile: ""
# Valid ssl hostname
mongodb_net_ssl_host: ""

# security variables
# Enable/Disable authorization
mongodb_security_authorization: disabled
# Enable/Disable javascript
mongodb_security_javascript_enabled: true
# MongoDB user password update default policy
mongodb_user_update_password: "on_create"

# custom config options
mongodb_config:
# Enable/Disable journal
mongodb_storage_journal_enabled: true

# names and passwords for administrative users
# Name of the user for administrative tasks
mongodb_user_admin_name: UserAdmin
# Password for the user for administrative tasks
mongodb_user_admin_password: passw01d

# Name of the user for root administrative tasks
mongodb_root_admin_name: RootAdmin
# Password for the user for root administrative tasks
mongodb_root_admin_password: passw01d

# Name of the user for backup tasks
mongodb_root_backup_name: BackupUser
# Password for the user for backup tasks
mongodb_root_backup_password: passw01d

# auth initialization variables
# Set PyMongo Version, default will install latest
mongodb_pymongo_pip_version:
mongodb_pymongo_package: python3-pymongo

# THP variables
mongodb_transparent_hugepages_optimization: false
