platform = {
  data-01 = {
    role         = "Lab Data Infrastructure"
    description  = "Lab Database Infrastructure VM Hosting Data and Storage Services."
    on_boot      = true
    name         = "data-01"
    node_name    = "platform-01"
    vm_id        = 102
    clone_vm_id  = 9999
    cores        = 4
    memory_mb    = 16384
    disk_size    = 100
    datastore_id = "vm-storage"
    bridge       = "vmbr0"
    ip_address   = "192.168.0.213/24"
    gateway      = "192.168.0.1"
  }
  k3s-control-01 = {
    role         = "K3s control plane node"
    description  = "K3s control plane node VM Hosting Kubernetes Control Plane Services."
    on_boot      = true
    name         = "k3s-control-01"
    node_name    = "platform-01"
    vm_id        = 103
    clone_vm_id  = 9999
    cores        = 4
    memory_mb    = 8192
    disk_size    = 50
    datastore_id = "vm-storage"
    bridge       = "vmbr0"
    ip_address   = "192.168.0.217/24"
    gateway      = "192.168.0.1"
  }
  k3s-worker-01 = {
    role         = "K3s Worker Node"
    description  = "K3s Worker Node VM Hosting Kubernetes Worker Services. - Apps, Automation and Observability"
    on_boot      = true
    name         = "k3s-worker-01"
    node_name    = "platform-01"
    vm_id        = 104
    clone_vm_id  = 9999
    cores        = 6
    memory_mb    = 24576
    disk_size    = 150
    datastore_id = "vm-storage"
    bridge       = "vmbr0"
    ip_address   = "192.168.0.215/24"
    gateway      = "192.168.0.1"
  }
  k3s-worker-02 = {
    role         = "K3s Worker Node"
    description  = "K3s Worker Node VM Hosting Kubernetes Worker Services. - AI and Dev Platform"
    on_boot      = true
    name         = "k3s-worker-02"
    node_name    = "platform-01"
    vm_id        = 105
    clone_vm_id  = 9999
    cores        = 6
    memory_mb    = 49152
    disk_size    = 150
    datastore_id = "vm-storage"
    bridge       = "vmbr0"
    ip_address   = "192.168.0.216/24"
    gateway      = "192.168.0.1"
  }
}

## HP Mini Proxmox VM's
infrastructure = {
  network-01 = {
    role             = "Network Node"
    description      = "Network Node VM Hosting Core Network Services."
    start_on_boot    = true
    hostname         = "network-01"
    node_name        = "infra-01"
    template_file_id = "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
    os_type          = "ubuntu"
    unprivileged     = true
    ssh_keys         = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqeXrJg9JAWDxBXGP/EhE4NV/cyBEy4bSfhoIilSw5L TechnicallyAustin@gmail.com"
    nesting          = true
    started          = true
    vm_id            = 106
    cores            = 2
    memory_mb        = 2048
    disk_size        = 32
    datastore_id     = "local-lvm"
    bridge           = "vmbr0"
    ip_address       = "192.168.0.211/24"
    gateway          = "192.168.0.1"
  }
  infra-01 = {
    role             = "Core Infrastructure Node"
    description      = "Core Infrastructure Node VM Hosting Core Infrastructure Services."
    start_on_boot    = true
    hostname         = "core-infra-01"
    node_name        = "infra-01"
    template_file_id = "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
    os_type          = "ubuntu"
    unprivileged     = true
    ssh_keys         = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqeXrJg9JAWDxBXGP/EhE4NV/cyBEy4bSfhoIilSw5L TechnicallyAustin@gmail.com"
    nesting          = true
    started          = true
    vm_id            = 107
    cores            = 2
    memory_mb        = 2048
    disk_size        = 32
    datastore_id     = "local-lvm"
    bridge           = "vmbr0"
    ip_address       = "192.168.0.212/24"
    gateway          = "192.168.0.1"
  }
}