---
- name: Kuberentes Compute platform
  hosts: k3s
  become: true
  vars:
    k3s_release_version: "v1.32.0+k3s1"
    k3s_become: true
    k3s_registration_address: "192.168.0.217"
    k3s_server_manifests_templates:
      - "{{ playbook_dir }}/../roles/k3s/templates/argocd-helmchart.yaml.j2"
  roles:
    - role: k3s

  post_tasks:
    - name: Fetch k3s kubeconfig to Mac
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/lab-config"
        flat: true
      become: true
      run_once: true
      delegate_to: k3s_control_01

    - name: Fix kubeconfig server address
      ansible.builtin.replace:
        path: "{{ lookup('env', 'HOME') }}/.kube/lab-config"
        regexp: 'https://127\.0\.0\.1:6443'
        replace: 'https://192.168.0.217:6443'
      delegate_to: localhost
      become: false
      run_once: true
